language: python
jobs:
  allow_failures:
    os:
      - osx
  include:
    - os: linux
      dist: bionic
      services:
        - xvfb
      name: "Python 3.7 on Bionic Linux"
      python:
        - 3.7
    - os: linux
      dist: bionic
      services:
        - xvfb
      name: "Python 3.8 on Bionic Linux"
      python: 3.8
    - os: osx
      osx_image: xcode11
      language: shell
      name: "Python 3.8 on macOS"
    - os: windows
      language: shell
      before_install:
        - choco install python --version=3.7.7
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      name: "Python 3.7 on Windows"
    - os: windows
      language: shell
      before_install:
        - choco install python3
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      name: "Python 3.8 on Windows"
addons:
  apt:
    packages:
      - x11-utils
      - libxkbcommon-x11-0
      - libxcb-keysyms1-dev
      - libx11-xcb-dev
      - herbstluftwm
install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then py -m pip install -r requirements.txt; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export DISPLAY=:99.0; /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset;sleep 3;pip3 install -r requirements.txt; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pip3 install -r requirements.txt; fi
script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ];then pytest -vxrs --cov=./; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pytest -vxrs --cov=./; fi
  - ldd `python -c 'import PySide2; import os.path; print(os.path.join(os.path.dirname(PySide2.__file__), "Qt", "plugins", "platforms", "libqxcb.so"))'`
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pytest -vxrs; fi
  - codecov
