dist: bionic
services:
  - xvfb
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  apt:
    packages:
      - build-essential
      - libssl-dev
      - libffi-dev
      - pkg-config
      - python3-cairo
      - libcairo2*
      - x11-utils
      - libxkbcommon-x11-0
install:
  - pip install -r requirements_linux.txt
script:
  pytest
