language: python
dist: bionic
jobs:
  allow_failures:
    - os:
      - osx
      - windows
  include:
    - os: linux
      dist: bionic
      services:
        - xvfb
      name: "Python 3.7 on Bionic Linux"
      python:
        - 3.7
    - os: linux
      dist: bionic
      services:
        - xvfb
      name: "Python 3.8 on Bionic Linux"
      python: 3.8
    - os: osx
      osx_image: xcode11
      language: shell
      name: "Python 3.8 on macOS"
      before_install:
        - sudo port install cairo
    - os: windows
    language: shell
    before_install:
      - choco install python --version=3.7.7
      - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      name: "Python 3.7 on Windows"
    - os: windows
      language: shell
      before_install:
        - choco install python  # this install takes at least 1 min 30 sec
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      name: "Python 3.8 on Windows"
addons:
  apt:
    packages:
      - build-essential
      - libssl-dev
      - libffi-dev
      - pkg-config
      - python3-cairo
      - libcairo2*
      - x11-utils
      - libxkbcommon-x11-0
install:
  - pip install -r requirements_linux.txt
script:
  pytest
