dist: bionic
services:
  - xvfb
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  apt:
    packages:
      - build-essential
      - libssl-dev
      - libffi-dev
      - pkg-config
      - python3-cairo
      - libcairo2*
      - x11-utils
      - libxkbcommon-x11-0
install:
  #- "export DISPLAY=:99.0"
  #- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
  #- sleep 3
  - pip install -r requirements_linux.txt
script:
  pytest
